### ISSUE TITLE
Problem compiling the project

### ISSUE THREAD

**Issue by kapsule** [KeenMate/rollup-svelte-adminlte-template#1]
Hi @OndrejValenta.

first of all, thank you for the new repository to test adminlte from svelte. I have tested the new repository and I get the following error. Do I have to modify something to be able to compile the project?

![image](https://user-images.githubusercontent.com/3903687/148109673-bca4b58c-21f8-4ca6-83cd-4c61e430dc60.png)

**Comment by OndrejValenta** [comment]
It seems, and with NodeJS one never knows, like you have version of NodeJS older than v14 and that's causing the issue. We are using Node Version Manager (nvm) and the solutions runs with version 14 and 16.
![WindowsTerminal_KAa27lK5AE](https://user-images.githubusercontent.com/6738956/148128687-5828591d-5212-49bd-98ce-408ee3af5654.png)

**Comment by kapsule** [comment]
Hi @OndrejValenta. you are absolutely right!!! I have already upgraded to the latest version of node v17.0.3 and now it compiles correctly. Now there are a lot of warnings but I will check them. The important thing is that the project now starts correctly.

![image](https://user-images.githubusercontent.com/3903687/148244502-07c7cc35-9913-406d-b1f2-04b4844677b5.png)

**Comment by OndrejValenta** [comment]
Good, good.. We still have some cleaning to do.. for example the i18n is probably unnecessary for some projects so we will hide language picker in the top right corner, also page title in "chrome" tab should be updated, I know that @TheMaikXX was working on that yesterday but I'm not sure if it's already committed here

But you can play with it already..

**Comment by FilipJakab** [comment]
> @TheMaikXX was working on that yesterday but I'm not sure if it's already committed here

Yes, that should be done by now. As this is a template it requires new project to be created or manually fetching changes.
I also managed to add section for [HTML Title](https://github.com/KeenMate/rollup-svelte-adminlte-template#html-title) in README to mention this feature together with how to configure it.

**Comment by OndrejValenta** [comment]
I will close this issue and if you have something else that requires our attention, let us know.
